install-python:
	echo "installing Python3..."
	-sudo apt-get install python3
	echo "installing pip3..."
	-sudo apt-get install python3-pip
	echo "installing Python dependencies..."
	cd ../../../src
	-sudo pip install -r requirements.txt
	echo "run python code"